//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursWorkWPF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dish
    {
        public int id { get; set; }
        public string names { get; set; }
        public string descriptions { get; set; }
        public int weights { get; set; }
        public byte[] photo { get; set; }
        public Nullable<decimal> price { get; set; }
    }
}
