//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursWorkWPF.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestorauntEntities : DbContext
    {
        private static RestorauntEntities context;
        public RestorauntEntities()
            : base("name=RestorauntEntities")
        {
        }
    public static RestorauntEntities GetContext()
        {
            if(context == null)
                context = new RestorauntEntities();
            return context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Book { get; set; }
        public virtual DbSet<Dish> Dish { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderContaint> OrderContaint { get; set; }
        public virtual DbSet<Place> Place { get; set; }
        public virtual DbSet<Restoraunt> Restoraunt { get; set; }
        public virtual DbSet<Table> Table { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
