//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursWorkWPF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderContaint
    {
        public int id { get; set; }
        public int order { get; set; }
        public int dish { get; set; }
    }
}
