//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursWorkWPF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restoraunt
    {
        public int id { get; set; }
        public string addres { get; set; }
        public Nullable<System.TimeSpan> openTime { get; set; }
        public Nullable<System.TimeSpan> closeTime { get; set; }
    }
}
