//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursWorkWPF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int id { get; set; }
        public int persons { get; set; }
        public int place { get; set; }
        public byte[] photo { get; set; }
        public int isFree { get; set; }
        public int restaurant { get; set; }
    }
}
